apiVersion: 1
datasources:
  - name: Jointbox
    type: postgres
    uid: jointbox-pg
    access: proxy
    url: ${JB_DB_HOST}:5432
    database: ${JB_DB_NAME}
    user: ${JB_DB_USER}
    secureJsonData:
      password: ${JB_DB_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1400
      timescaledb: false
    isDefault: true
    editable: true
